import { Octokit } from 'octokit'
import type { CreatePullRequestResult } from './types'

export function buildPRBody(
  language: string,
  files: Array<{ original: string; translated: string }>,
): string {
  const fileRows = files
    .map(f => `| ${f.original} | ${f.translated} |`)
    .join('\n')

  return `## 🌍 DocBridge Translation PR

This PR adds translated documentation generated by **DocBridge**.

### Translated Languages

- ${language}

### Translated Files

| Original | Translated |
|----------|-----------|
${fileRows}

Please review the translation accuracy before merging.

Generated by DocBridge.`
}

export async function createPullRequest(
  token: string,
  owner: string,
  repo: string,
  options: {
    title: string
    body: string
    head: string
    base: string
  },
): Promise<CreatePullRequestResult> {
  const octokit = new Octokit({ auth: token })
  const { data } = await octokit.rest.pulls.create({
    owner,
    repo,
    title: options.title,
    body: options.body,
    head: options.head,
    base: options.base,
  })
  return {
    number: data.number,
    url: data.html_url,
    title: data.title,
  }
}
