// Example: How to integrate translation-storage into DocBridge workflow
// This shows the complete flow from detection to PR creation

import { detectMultiLangPattern, getTranslationPlacement, type MultiLangPattern } from '@docbridge/core'
import { getTree } from '@docbridge/github'
import type { TranslationProvider } from '@docbridge/ai'

interface TranslationResult {
  originalPath: string
  targetPath: string
  content: string
  createDirectory: boolean
}

/**
 * Step 1: Get repository file list for pattern detection
 */
async function getRepositoryFiles(owner: string, repo: string, token: string): Promise<string[]> {
  const tree = await getTree(owner, repo, 'HEAD', token, true)
  return tree
    .filter(item => item.type === 'blob')
    .map(item => item.path)
}

/**
 * Step 2: Detect multi-language pattern
 */
async function detectRepoPattern(owner: string, repo: string, token: string): Promise<MultiLangPattern> {
  const files = await getRepositoryFiles(owner, repo, token)
  const pattern = detectMultiLangPattern(files)

  console.log(`Detected pattern: ${pattern.type}`)
  if (pattern.baseDir) {
    console.log(`Base directory: ${pattern.baseDir}`)
  }

  return pattern
}

/**
 * Step 3: Translate files with intelligent placement
 */
async function translateFiles(
  owner: string,
  repo: string,
  token: string,
  filesToTranslate: string[],
  targetLocale: string,
  provider: TranslationProvider,
) {
  // Detect pattern once for all files
  const pattern = await detectRepoPattern(owner, repo, token)

  const translations = []

  for (const filePath of filesToTranslate) {
    // Get file content
    const content = await getFileContent(owner, repo, filePath, token)

    // Translate
    const translated = await translateDocument(content, targetLocale, provider)

    // Determine placement
    const placement = getTranslationPlacement(filePath, targetLocale, pattern)

    translations.push({
      originalPath: filePath,
      targetPath: placement.targetPath,
      content: translated,
      createDirectory: placement.createDirectory,
    })

    console.log(`${filePath} → ${placement.targetPath}`)
  }

  return { translations, pattern }
}

/**
 * Step 4: Create PR with translated files
 */
async function createTranslationPR(
  owner: string,
  repo: string,
  token: string,
  translations: TranslationResult[],
  pattern: MultiLangPattern,
  targetLocale: string,
) {
  // Fork repository
  const fork = await forkRepository(owner, repo, token)

  // Create branch
  const branchName = `translate-to-${targetLocale}-${Date.now()}`
  await createBranch(fork.owner, fork.repo, branchName, token)

  // Commit translated files
  for (const translation of translations) {
    // Create directory structure if needed
    if (translation.createDirectory) {
      const dir = translation.targetPath.split('/').slice(0, -1).join('/')
      console.log(`Creating directory: ${dir}`)
    }

    // Commit file
    await createOrUpdateFile(
      fork.owner,
      fork.repo,
      translation.targetPath,
      translation.content,
      `Add ${targetLocale} translation for ${translation.originalPath}`,
      branchName,
      token,
    )
  }

  // Create pull request
  const prTitle = `Add ${targetLocale} translations`
  const prBody = `
## Translation Summary

- **Target Language**: ${targetLocale}
- **Files Translated**: ${translations.length}
- **Pattern Detected**: ${pattern.type}${pattern.baseDir ? ` (${pattern.baseDir})` : ''}

### Files

${translations.map(t => `- ${t.originalPath} → ${t.targetPath}`).join('\n')}

---

*This PR was automatically generated by [DocBridge](https://github.com/yourusername/docbridge)*
  `.trim()

  const pr = await createPullRequest(
    owner,
    repo,
    fork.owner,
    branchName,
    prTitle,
    prBody,
    token,
  )

  return pr
}

/**
 * Complete workflow example
 */
async function translateAndCreatePR(
  owner: string,
  repo: string,
  token: string,
  filesToTranslate: string[],
  targetLocale: string,
  provider: TranslationProvider,
) {
  console.log('Starting translation workflow...')

  // Step 1: Detect pattern
  console.log('\n1. Detecting multi-language pattern...')
  const pattern = await detectRepoPattern(owner, repo, token)

  // Step 2: Translate files
  console.log('\n2. Translating files...')
  const { translations } = await translateFiles(
    owner,
    repo,
    token,
    filesToTranslate,
    targetLocale,
    provider,
  )

  // Step 3: Create PR
  console.log('\n3. Creating pull request...')
  const pr = await createTranslationPR(
    owner,
    repo,
    token,
    translations,
    pattern,
    targetLocale,
  )

  console.log(`\n✓ Pull request created: ${pr.html_url}`)

  return pr
}

/**
 * Usage in API route
 */
// apps/web/src/app/api/translate/route.ts
export async function POST(request: Request) {
  const { owner, repo, files, targetLocale, providerId } = await request.json()
  const token = cookies().get('gh_token')?.value

  if (!token) {
    return NextResponse.json({ error: 'Not authenticated' }, { status: 401 })
  }

  try {
    // Get provider
    const provider = await createProvider(providerId)

    // Translate and create PR
    const pr = await translateAndCreatePR(
      owner,
      repo,
      token,
      files,
      targetLocale,
      provider,
    )

    return NextResponse.json({
      success: true,
      prUrl: pr.html_url,
      prNumber: pr.number,
    })
  } catch (error) {
    console.error('Translation failed:', error)
    return NextResponse.json(
      { error: 'Translation failed' },
      { status: 500 },
    )
  }
}

/**
 * Example: Handling different patterns
 */
async function demonstratePatterns() {
  // Example 1: Repository with docs/locale structure
  const files1 = [
    'README.md',
    'docs/en/guide.md',
    'docs/zh/guide.md',
  ]
  const pattern1 = detectMultiLangPattern(files1)
  console.log(pattern1) // { type: 'docs-subdir', baseDir: 'docs' }

  const placement1 = getTranslationPlacement('docs/en/api.md', 'fr', pattern1)
  console.log(placement1) // { targetPath: 'docs/fr/api.md', createDirectory: true }

  // Example 2: Repository with root suffix
  const files2 = [
    'README.md',
    'README.zh.md',
    'README.ja.md',
  ]
  const pattern2 = detectMultiLangPattern(files2)
  console.log(pattern2) // { type: 'root-suffix' }

  const placement2 = getTranslationPlacement('README.md', 'fr', pattern2)
  console.log(placement2) // { targetPath: 'README.fr.md', createDirectory: false }

  // Example 3: Repository with no pattern (first translation)
  const files3 = [
    'README.md',
    'docs/guide.md',
    'src/index.ts',
  ]
  const pattern3 = detectMultiLangPattern(files3)
  console.log(pattern3) // { type: 'none' }

  // Root file uses suffix
  const placement3a = getTranslationPlacement('README.md', 'zh', pattern3)
  console.log(placement3a) // { targetPath: 'README.zh.md', createDirectory: false }

  // Nested file creates locale subdir
  const placement3b = getTranslationPlacement('docs/guide.md', 'zh', pattern3)
  console.log(placement3b) // { targetPath: 'docs/zh/guide.md', createDirectory: true }
}

export {
  getRepositoryFiles,
  detectRepoPattern,
  translateFiles,
  createTranslationPR,
  translateAndCreatePR,
  demonstratePatterns,
}
